/** Créditos y origen de los recursos. */
import { h } from './dom.js';
import { Screen } from './UIManager.js';
import { L } from '../core/i18n.js';
import { LOGO_SVG } from './MainMenu.js';

export class CreditsScreen extends Screen {
  build() {
    return h('div', { class: 'screen dim' },
      this.head(L('Créditos', 'Credits'), 'RC FLIGHT SIMULATOR v1.0'),
      h('div', { class: 'scroll', style: { flex: 1 } },
        h('div', { class: 'credits' },
          h('div', { class: 'logo' }, h('span', { html: LOGO_SVG }).firstChild, h('div', { class: 'wordmark' }, h('b', {}, 'RC FLIGHT'), h('span', {}, 'SIMULATOR'))),
          h('p', {}, L('Simulador de aeromodelismo de radiocontrol con identidad propia, inspirado en la claridad de los simuladores RC clásicos. Todo el contenido —modelos 3D, escenarios, texturas y sonidos— se genera por código en tiempo real; no se usan recursos de terceros.', 'A radio-control model flight simulator with its own identity, inspired by the clarity of classic RC simulators. All content —3D models, scenery, textures and sounds— is generated by code at runtime; no third-party assets are used.')),
          h('h3', {}, L('Tecnología', 'Technology')),
          h('p', {}, 'Three.js r186 (MIT) · WebGL2 · Web Audio API · Gamepad API · Pointer Events · IndexedDB · JavaScript ES2022'),
          h('h3', {}, L('Modelo de vuelo', 'Flight model')),
          h('p', {}, L('Dinámica de sólido rígido de 6 grados de libertad con modelo aerodinámico por paneles (sustentación, resistencia, resistencia inducida, pérdida en 360°, efecto suelo, estela de la hélice, par motor y efecto giroscópico), integrada con paso fijo de 240 Hz.', 'Six-degree-of-freedom rigid-body dynamics with a panel-based aerodynamic model (lift, drag, induced drag, 360° stall, ground effect, prop wash, engine torque and gyroscopic effect), integrated at a fixed 240 Hz step.')),
          h('h3', {}, L('Aeronaves', 'Aircraft')),
          h('p', {}, L('Los nombres de modelos reales (Cessna, Piper, Extra, Edge, Sukhoi, Yak, CAP, L-39, F-16, F-18, P-51, Spitfire, Pitts) identifican el tipo de maqueta RC representada. Los modelos 3D y sus decoraciones son interpretaciones originales y no reproducen marcas ni insignias oficiales.', 'Real aircraft names (Cessna, Piper, Extra, Edge, Sukhoi, Yak, CAP, L-39, F-16, F-18, P-51, Spitfire, Pitts) identify the type of RC scale model represented. 3D models and liveries are original interpretations and do not reproduce official trademarks or insignia.')),
          h('h3', {}, L('Tipografías', 'Fonts')),
          h('p', {}, 'Inter, Rajdhani y JetBrains Mono (SIL Open Font License) vía Google Fonts, con alternativas del sistema si no hay conexión.'))));
  }
}
